import '../global.css';
import Banner from '../component/banner/Banner';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="bg-[#10141E] w-full max-w-[1650px] text-white">
        <Banner />
        <main className="pl-[156px] mt-[2%]">{children}</main>
      </body>
    </html>
  );
}
